TOOLS=~/.tools

ZSH=$TOOLS/zsh
source $ZSH/zplug.zsh
source $ZSH/aliases.zsh
source $ZSH/history.zsh
source $ZSH/keybindings.zsh
source $ZSH/prompt.zsh

export PATH=~/.bin:$PATH

source $TOOLS/bat/zsh
source $TOOLS/brew/zsh
source $TOOLS/bril.zsh
source $TOOLS/deno.zsh
source $TOOLS/deno-deploy.zsh
source $TOOLS/python/zsh
source $TOOLS/vscode/zsh
source $TOOLS/firefox.zsh
source $TOOLS/fzf.zsh
source $TOOLS/gh.zsh
source $TOOLS/man.zsh
source $TOOLS/node.zsh
