#!/usr/bin/env zsh

# pyenv
#######

# https://github.com/pyenv/pyenv#installation
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# poetry
########

export PATH="$HOME/.poetry/bin:$PATH"
# https://poetry.eustace.io/docs/#installation
alias poe="poetry run"
